---
name: "Bookshelf"
guid: "9c4e63f1-031b-4f25-988b-4f7d78a8b53e"
version: 10
targetAbi: "10.8.13.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Manage your books"
description: >
  Supports several different metadata providers and options for organizing your collection.

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.Bookshelf.dll"
changelog: |-
  - Add Unit tests for ComicInfo and ComicBookInfo formats (#70) @carif

  ### New features and improvements ###
  - Add Comic Vine metadata provider (#81) @Pithaya
  - Add Google Books external id (#80) @Pithaya
  - Add unit tests for the Google Books providers (#78) @Pithaya
  - Improve title handling of epub files (#75) @carif

  ### Bug Fixes ###
  - Update EpubMetadataImageProvider.cs (#66) @wuyu8512

  ### Documentation updates ###
  - Fix typo and improve README formatting (#74) @carif

  ### Dependency updates ###
  - Update xunit-dotnet monorepo to v2.5.3 (#82) @renovate
