---
name: "Bookshelf"
guid: "9c4e63f1-031b-4f25-988b-4f7d78a8b53e"
version: 12
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Manage your books"
description: >
  Supports several different metadata providers and options for organizing your collection.

category: "Books"
artifacts:
  - "Jellyfin.Plugin.Bookshelf.dll"
  - "Docnet.Core.dll"
  - "SharpCompress.dll"
  - "SkiaSharp.dll"
  - "ZstdSharp.dll"
  - "pdfium.so"
changelog: |-
  - Fix nullability for 10.10 (#116) @crobibero
  - Update opf and add ISBN (#108) @AshleyDeo
  - Add Comic Vine Person provider (#85) @Pithaya

  ### New features and improvements ###
  - Add support for covers from .cbt, .cb7 and .cbr (#112) @oddstr13

  ### Dependency updates ###
  - Update dependency Microsoft.NET.Test.Sdk to 17.11.1 (#106) @renovate
  - Update xunit-dotnet monorepo (#84) @renovate
  - Update dependency Microsoft.Extensions.Http to 8.0.1 - autoclosed (#115) @renovate
