---
name: "Bookshelf"
guid: "9c4e63f1-031b-4f25-988b-4f7d78a8b53e"
version: 13
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Manage your books"
description: >
  Supports several different metadata providers and options for organizing your collection.

category: "Books"
artifacts:
  - "Jellyfin.Plugin.Bookshelf.dll"
  - "SharpCompress.dll"
  - "ZstdSharp.dll"
  - "PDFtoImage.dll"
  - "SkiaSharp.dll"
  - "runtimes/linux-arm64/native/libpdfium.so"
  - "runtimes/linux-x64/native/libpdfium.so"
  - "runtimes/osx-arm64/native/libpdfium.dylib"
  - "runtimes/osx-x64/native/libpdfium.dylib"
  - "runtimes/win-arm64/native/pdfium.dll.win"
  - "runtimes/win-x64/native/pdfium.dll.win"
changelog: |-
  - Jellyfin 10.11 support (#130) @crobibero
