---
name: "Bookshelf"
guid: "9c4e63f1-031b-4f25-988b-4f7d78a8b53e"
version: 13
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Manage your books"
description: >
  Supports several different metadata providers and options for organizing your collection.

category: "Books"
artifacts:
  - "Jellyfin.Plugin.Bookshelf.dll"
  - "SharpCompress.dll"
  - "ZstdSharp.dll"
changelog: |-
  - Jellyfin 10.11 support (#130) @crobibero
