name: '🏗️ Build Plugin'

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/build.yaml@3e7e3bfc493a71e2dc9523127de0982a24639a0c # master
