# Allows for the definition of PR and Issue /commands
name: '📟 Slash Command Dispatcher'

on:
  issue_comment:
    types:
      - created

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/command-dispatch.yaml@3e7e3bfc493a71e2dc9523127de0982a24639a0c # master
    secrets:
      token: ${{ secrets.JF_BOT_TOKEN }}
