name: '🚀 Publish Plugin'

on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/publish.yaml@3e7e3bfc493a71e2dc9523127de0982a24639a0c # master
    with:
      version: ${{ github.event.release.tag_name }}
      is-unstable: ${{ github.event.release.prerelease }}
    secrets:
      deploy-host: ${{ secrets.REPO_HOST }}
      deploy-user: ${{ secrets.REPO_USER }}
      deploy-key: ${{ secrets.REPO_KEY }}
