name: '🏷️ Sync labels'

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/sync-labels.yaml@3e7e3bfc493a71e2dc9523127de0982a24639a0c # master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
